language: r
cache: packages
latex: false
r_build_args: --no-build-vignettes
r_check_args: --as-cran --ignore-vignettes

# This is the minimal set of R packages needed to run "R CMD check" on
# the package.
install:
  - R -e 'install.packages(c("devtools","covr","testthat","mvtnorm","Rcpp","RcppArmadillo","knitr","rmarkdown"))'

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_: false
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

after_success:
  - Rscript -e 'library(covr); codecov()'

branches:
  only:
    - master
